column_width = 160

line_endings = "Unix"
indent_type = "Spaces"
indent_width = 4
quote_style = "AutoPreferDouble"
call_parentheses = "Always"
syntax = "Lua51"

# Readability & Git Performance
collapse_simple_statement = "FunctionOnly"

[sort_requires]
enabled = false
